Controllers/PeopleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Universidad.Models;

namespace Universidad.Controllers
{
    [Authorize]
    public class PeopleController : Controller
    {
        private readonly UniversidadContext _context;

        public PeopleController(UniversidadContext context)
        {
            _context = context;
        }

        // GET: Personas
        public async Task<IActionResult> Index()
        {
              return _context.Personas != null ? 
                          View(await _context.Personas.ToListAsync()) :
                          Problem("Entity set 'UniversidadContext.Personas'  is null.");
        }

        // GET: Personas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Personas == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas
                .FirstOrDefaultAsync(m => m.IdPersona == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // GET: Personas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Personas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPersona,Matricula,Nombre,Apellido,Edad,Genero,Cedula,Correo,NumCelular,NumTelefono,Direccion")] Persona persona)
        {
            if (ModelState.IsValid)
            {
                _context.Add(persona);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Personas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Personas == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas.FindAsync(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        // POST: Personas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPersona,Matricula,Nombre,Apellido,Edad,Genero,Cedula,Correo,NumCelular,NumTelefono,Direccion")] Persona persona)
        {
            if (id != persona.IdPersona)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(persona);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonaExists(persona.IdPersona))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Personas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Personas == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas
                .FirstOrDefaultAsync(m => m.IdPersona == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Personas == null)
            {
                return Problem("Entity set 'UniversidadContext.Personas'  is null.");
            }
            var persona = await _context.Personas.FindAsync(id);
            if (persona != null)
            {
                _context.Personas.Remove(persona);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonaExists(int id)
        {
          return (_context.Personas?.Any(e => e.IdPersona == id)).GetValueOrDefault();
        }
    }
}

Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Universidad.Models;

namespace Universidad.Controllers
{
    [Authorize]
    public class StudentsController : Controller
    {
        private readonly UniversidadContext _context;

        public StudentsController(UniversidadContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var universidadContext = _context.Estudiantes.Include(e => e.IdCarreraNavigation).Include(e => e.IdPersonaNavigation);
            return View(await universidadContext.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Estudiantes == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes
                .Include(e => e.IdCarreraNavigation)
                .Include(e => e.IdPersonaNavigation)
                .FirstOrDefaultAsync(m => m.IdEstudiantes == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            ViewData["IdCarrera"] = new SelectList(_context.Carreras, "IdCarrera", "IdCarrera");
            ViewData["IdPersona"] = new SelectList(_context.Personas, "IdPersona", "IdPersona");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdEstudiantes,IdPersona,IdCarrera")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estudiante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCarrera"] = new SelectList(_context.Carreras, "IdCarrera", "IdCarrera", estudiante.IdCarrera);
            ViewData["IdPersona"] = new SelectList(_context.Personas, "IdPersona", "IdPersona", estudiante.IdPersona);
            return View(estudiante);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Estudiantes == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes.FindAsync(id);
            if (estudiante == null)
            {
                return NotFound();
            }
            ViewData["IdCarrera"] = new SelectList(_context.Carreras, "IdCarrera", "IdCarrera", estudiante.IdCarrera);
            ViewData["IdPersona"] = new SelectList(_context.Personas, "IdPersona", "IdPersona", estudiante.IdPersona);
            return View(estudiante);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdEstudiantes,IdPersona,IdCarrera")] Estudiante estudiante)
        {
            if (id != estudiante.IdEstudiantes)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estudiante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstudianteExists(estudiante.IdEstudiantes))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCarrera"] = new SelectList(_context.Carreras, "IdCarrera", "IdCarrera", estudiante.IdCarrera);
            ViewData["IdPersona"] = new SelectList(_context.Personas, "IdPersona", "IdPersona", estudiante.IdPersona);
            return View(estudiante);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Estudiantes == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes
                .Include(e => e.IdCarreraNavigation)
                .Include(e => e.IdPersonaNavigation)
                .FirstOrDefaultAsync(m => m.IdEstudiantes == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Estudiantes == null)
            {
                return Problem("Entity set 'UniversidadContext.Estudiantes'  is null.");
            }
            var estudiante = await _context.Estudiantes.FindAsync(id);
            if (estudiante != null)
            {
                _context.Estudiantes.Remove(estudiante);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstudianteExists(int id)
        {
          return (_context.Estudiantes?.Any(e => e.IdEstudiantes == id)).GetValueOrDefault();
        }
    }
}

Views/Students/Create.cshtml
@model Universidad.Models.Estudiante

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Estudiante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPersona" class="control-label"></label>
                <select asp-for="IdPersona" class ="form-control" asp-items="ViewBag.IdPersona"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdCarrera" class="control-label"></label>
                <select asp-for="IdCarrera" class ="form-control" asp-items="ViewBag.IdCarrera"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Students/Delete.cshtml
@model Universidad.Models.Estudiante

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Estudiante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCarreraNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCarreraNavigation.IdCarrera)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPersonaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPersonaNavigation.IdPersona)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdEstudiantes" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Students/Details.cshtml
@model Universidad.Models.Estudiante

@{
    ViewData["Title"] = "Details";
}

<div class="pagetitle">
    <h1>Details</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Students">Students</a></li>
            <li class="breadcrumb-item active">Profile</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<section class="section profile">
    <div class="row">
        <div class="col-xl-4">

            <div class="card">
                <div class="card-body profile-card pb-3 d-flex flex-column align-items-center">
                    <div class="w-75 text-end">
                        <a asp-controller="People" asp-action="Edit" asp-route-id="@Model?.IdEstudiantes" type="button" class="btn btn-sm btn-warning">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                    </div>

                    @if (Model.IdPersonaNavigation.Genero.Equals("M"))
                    {
                        <img src="~/img/male.png" alt="Profile" class="rounded-circle">
                    } else
                    {
                        <img src="~/img/female.png" alt="Profile" class="rounded-circle">
                    }
                    <h2  class="mb-2">@Model.IdPersonaNavigation.Nombre @Model.IdPersonaNavigation.Apellido</h2>
                    <h3>Student</h3>
                </div>
            </div>

        </div>

        <div class="col-xl-8">

            <div class="card">
                <div class="card-body pt-3">
                    <!-- Bordered Tabs -->
                    <ul class="nav nav-tabs nav-tabs-bordered">

                        <li class="nav-item">
                            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                        </li>

                        <li class="nav-item">
                            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Contact Profile</button>
                        </li>

                    </ul>
                    <div class="tab-content pt-2">

                        <div class="tab-pane fade show active profile-overview ps-3" id="profile-overview">
                            <h5 class="card-title">Profile Details</h5>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Identification Card Number</div>
                                <div class="col-lg-9 col-md-8">@Model.IdPersonaNavigation.Cedula</div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label ">University Registration Number</div>
                                <div class="col-lg-9 col-md-8">@Model.IdPersonaNavigation.Matricula</div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label ">Gender</div>
                                <div class="col-lg-9 col-md-8">@Model.IdPersonaNavigation.Genero</div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label ">Age</div>
                                <div class="col-lg-9 col-md-8">@Model.IdPersonaNavigation.Edad</div>
                            </div>
                        </div>

                        <div class="tab-pane fade show profile-overview ps-3" id="profile-edit">
                            <h5 class="card-title">Information</h5>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Email</div>
                                <div class="col-md-8 col-lg-9">
                                    @Model.IdPersonaNavigation.Correo
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Phone</div>
                                <div class="col-md-8 col-lg-9">
                                    @Model.IdPersonaNavigation.NumCelular
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Home Phone</div>
                                <div class="col-md-8 col-lg-9">
                                    @Model.IdPersonaNavigation.NumTelefono
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Address</div>
                                <div class="col-md-8 col-lg-9">
                                    @Model.IdPersonaNavigation.Direccion
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Students/Edit.cshtml
@model Universidad.Models.Estudiante
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Edit";
}

@if(User.IsInRole("Admin")) {
    <h1>Edit</h1>

    <h4>Estudiante</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="IdEstudiantes" />
                <div class="form-group">
                    <label asp-for="IdPersona" class="control-label"></label>
                    <select asp-for="IdPersona" class="form-control" asp-items="ViewBag.IdPersona"></select>
                    <span asp-validation-for="IdPersona" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IdCarrera" class="control-label"></label>
                    <select asp-for="IdCarrera" class="form-control" asp-items="ViewBag.IdCarrera"></select>
                    <span asp-validation-for="IdCarrera" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
    @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
} else {
    <h1 class="text-danger">Access Denied</h1>
}

Views/Students/Index.cshtml
@model IEnumerable<Universidad.Models.Estudiante>

@{
    ViewData["Title"] = "Students";
}

<div class="pagetitle d-flex justify-content-between">
    <div class="pagetitle">
        <h1>Teachers</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item">Students</li>
            </ol>
        </nav>
    </div>

    <div class="d-flex align-items-center">
        <button type="button" class="btn btn-outline-primary h-50">
            <a class="text-decoration-none" asp-action="Create">Create New</a>
        </button>
    </div>
</div><!-- End Page Title -->

<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card overflow-auto">
                <div class="card-body">
                    <table class="table datatable">
                        <thead>
                            <tr>
                                <th scope="col">No.</th>
                                <th scope="col">Nombre y Apellido</th>
                                <th scope="col">Correo</th>
                                <th scope="col">Celular</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.OrderBy(p => p.IdEstudiantes))
                            {
                                <tr data-index="0">
                                    <td>@item.IdEstudiantes</td>
                                    <td>@item.IdPersonaNavigation.Nombre @item.IdPersonaNavigation.Apellido</td>
                                    <td>@item.IdPersonaNavigation.Correo</td>
                                    <td>@item.IdPersonaNavigation.NumCelular</td>
                                    <td>
                                        <a asp-action="Details" asp-route-id="@item.IdEstudiantes"><i class="bi bi-info-circle"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>