Controllers/CareersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Universidad.Models;

namespace Universidad.Controllers
{
    [Authorize]
    public class CareersController : Controller
    {
        private readonly UniversidadContext _context;

        public CareersController(UniversidadContext context)
        {
            _context = context;
        }

        // GET: Carreras
        public async Task<IActionResult> Index()
        {
            var universidadContext = _context.Carreras.Include(c => c.IdAreaNavigation);
            return View(await universidadContext.ToListAsync());
        }

        // GET: Carreras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Carreras == null)
            {
                return NotFound();
            }

            var carrera = await _context.Carreras
                .Include(c => c.IdAreaNavigation)
                .FirstOrDefaultAsync(m => m.IdCarrera == id);
            if (carrera == null)
            {
                return NotFound();
            }

            return View(carrera);
        }

        // GET: Carreras/Create
        public IActionResult Create()
        {
            ViewData["IdArea"] = new SelectList(_context.Areas, "IdArea", "IdArea");
            return View();
        }

        // POST: Carreras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCarrera,IdArea,Nombre,Descripcion")] Carrera carrera)
        {
            if (ModelState.IsValid)
            {
                _context.Add(carrera);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdArea"] = new SelectList(_context.Areas, "IdArea", "IdArea", carrera.IdArea);
            return View(carrera);
        }

        // GET: Carreras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Carreras == null)
            {
                return NotFound();
            }

            var carrera = await _context.Carreras.FindAsync(id);
            if (carrera == null)
            {
                return NotFound();
            }
            ViewData["IdArea"] = new SelectList(_context.Areas, "IdArea", "IdArea", carrera.IdArea);
            return View(carrera);
        }

        // POST: Carreras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCarrera,IdArea,Nombre,Descripcion")] Carrera carrera)
        {
            if (id != carrera.IdCarrera)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carrera);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarreraExists(carrera.IdCarrera))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdArea"] = new SelectList(_context.Areas, "IdArea", "IdArea", carrera.IdArea);
            return View(carrera);
        }

        // GET: Carreras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Carreras == null)
            {
                return NotFound();
            }

            var carrera = await _context.Carreras
                .Include(c => c.IdAreaNavigation)
                .FirstOrDefaultAsync(m => m.IdCarrera == id);
            if (carrera == null)
            {
                return NotFound();
            }

            return View(carrera);
        }

        // POST: Carreras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Carreras == null)
            {
                return Problem("Entity set 'UniversidadContext.Carreras'  is null.");
            }
            var carrera = await _context.Carreras.FindAsync(id);
            if (carrera != null)
            {
                _context.Carreras.Remove(carrera);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarreraExists(int id)
        {
          return (_context.Carreras?.Any(e => e.IdCarrera == id)).GetValueOrDefault();
        }
    }
}

Controllers/DeaneriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Universidad.Models;

namespace Universidad.Controllers
{
    [Authorize]
    public class DeaneriesController : Controller
	{
		private readonly UniversidadContext _context;

		public DeaneriesController(UniversidadContext context)
		{
			_context = context;
		}

		// GET: Deaneries
		public async Task<IActionResult> Index()
		{
			var departamentos = _context.Departamentos
			.Include(d => d.Areas)
			.ThenInclude(d => d.Carreras)
			.ToListAsync();

			return departamentos != null ?
					  View(await departamentos) :
					  Problem("Entity set 'UniversidadContext.Departamentos'  is null.");
		}

		// GET: Deaneries/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Departamentos == null)
			{
				return NotFound();
			}

			var departamento = await _context.Departamentos
				.FirstOrDefaultAsync(m => m.IdDepartamento == id);
			if (departamento == null)
			{
				return NotFound();
			}

			return View(departamento);
		}

		// GET: Deaneries/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Deaneries/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("IdDepartamento,Nombre")] Departamento departamento)
		{
			if (ModelState.IsValid)
			{
				_context.Add(departamento);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(departamento);
		}

		// GET: Deaneries/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Departamentos == null)
			{
				return NotFound();
			}

			var departamento = await _context.Departamentos.FindAsync(id);
			if (departamento == null)
			{
				return NotFound();
			}
			return View(departamento);
		}

		// POST: Deaneries/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("IdDepartamento,Nombre")] Departamento departamento)
		{
			if (id != departamento.IdDepartamento)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(departamento);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!DepartamentoExists(departamento.IdDepartamento))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(departamento);
		}

		// GET: Deaneries/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Departamentos == null)
			{
				return NotFound();
			}

			var departamento = await _context.Departamentos
				.FirstOrDefaultAsync(m => m.IdDepartamento == id);
			if (departamento == null)
			{
				return NotFound();
			}

			return View(departamento);
		}

		// POST: Deaneries/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Departamentos == null)
			{
				return Problem("Entity set 'UniversidadContext.Departamentos'  is null.");
			}
			var departamento = await _context.Departamentos.FindAsync(id);
			if (departamento != null)
			{
				_context.Departamentos.Remove(departamento);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool DepartamentoExists(int id)
		{
			return (_context.Departamentos?.Any(e => e.IdDepartamento == id)).GetValueOrDefault();
		}
	}
}

Views/Deaneries/Create.cshtml
@model Universidad.Models.Departamento

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Deaneries/Delete.cshtml
@model Universidad.Models.Departamento

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdDepartamento" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Deaneries/Details.cshtml
@model Universidad.Models.Departamento

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdDepartamento">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Deaneries/Edit.cshtml
@model Universidad.Models.Departamento

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdDepartamento" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Deaneries/Index.cshtml
@model IEnumerable<Universidad.Models.Departamento>

@{
    ViewData["Title"] = "Index";
    int i = 1;
}
@foreach (var departamento in Model)
{
    <div class="">
        <h2 class="text-center fw-bold">@departamento.Nombre</h2>
        <div class="d-flex justify-content-between align-items-baseline">

            @foreach (var area in departamento.Areas)
            {
                var pind = (100 / departamento.Areas.Count());
                var cp = pind - (pind / departamento.Areas.Count());

                if (cp != 0)
                {
                    <div style="width: @cp%; margin: 0 auto;">
                        <!-- Table with stripped rows -->
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col" class="card-title text-center" colspan="1">@area.Nombre</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var career in area.Carreras)
                                {
                                    <tr>
                                        <td>
                                            @career.Nombre
                                        </td>
                                        <td class="align-middle">
                                            <a asp-controller="Careers" asp-action="Details" asp-route-id="@career.IdCarrera"><i class="bi bi-info-circle"></i></a>
                                        </td>
                                    </tr>
                                    i++;
                                }
                                @{
                                    i = 1;
                                }
                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <div style="width: 25%; margin: 0 auto;">
                        <h5 class="card-title text-center">@area.Nombre</h5>

                        <!-- Table with stripped rows -->
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Careers</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var career in area.Carreras)
                                {
                                    <tr>
                                        <td>
                                            @career.Nombre
                                        </td>
                                        <td class="align-middle">
                                            <a asp-action="Details" asp-route-id="@career.IdCarrera"><i class="bi bi-info-circle"></i></a>
                                        </td>
                                    </tr>
                                    i++;
                                }
                                @{
                                    i = 1;
                                }
                            </tbody>
                        </table>
                    </div>
                }
            }
        </div>
    </div>
    <hr></hr>
}